services:
  db:
    image: postgres:15
    container_name: redmane-db
    restart: always
    environment:
      POSTGRES_DB: readmedatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./REDMANE_fastapi_public_data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - redmane-network

  backend:
    build:
      context: ./ 
      dockerfile: ./redmane_fastapi.dockerfile
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/readmedatabase
    depends_on:
      - db
    networks:
      - redmane-network

  frontend-build:
    build:
      context: ./ 
      dockerfile: ./redmane_reactjs.dockerfile
    volumes:
      - frontend-static:/static
    restart: "no"

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_SSL_PORT}:443"
    environment:
      DOMAINS: "${PORTAL_DOMAIN}"
      # Do not use production until ready because Let's Encrypt has rate limits
      STAGE: "${PORTAL_STAGE}" # local, 'staging', 'production'
    volumes:
      - https-portal-data:/var/lib/https-portal
      - ./${PORTAL_CONFIG}:/var/lib/nginx-conf/${PORTAL_CONFIG}:ro
      - frontend-static:/var/www/vhosts/data-registry:ro
    depends_on:
      backend:
        condition: service_started
      frontend-build:
        condition: service_completed_successfully
    networks:
      - redmane-network

volumes:
  postgres_data:
  https-portal-data:
  frontend-static:

networks:
  redmane-network:
    driver: bridge
